Repository Borewit/listFix, pull requests merged in 2023-02, with the labels that each got.

#49 Use gradle-build-action in GitHub action
  .github/workflows/ci.yml
Labels: DevOps

#51 Eliminate `com.jidesoft:jide-components` dependency
  build.gradle
  src/demos/ListDataEventDemo.java
  src/main/java/listfix/model/playlists/Playlist.java
  src/main/java/listfix/model/playlists/PlaylistEntry.java
  src/main/java/listfix/swing/IDocumentChangeListener.java
  src/main/java/listfix/swing/JButtonTabComponent.java
  src/main/java/listfix/swing/JDocumentComponent.java
  src/main/java/listfix/swing/JDocumentTabbedPane.java
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/controls/PlaylistEditCtrl.java
  src/main/java/listfix/view/dialogs/AppOptionsDialog.java
  src/main/java/listfix/view/dialogs/FolderChooser.java
  src/main/java/listfix/view/support/ICloseableTabManager.java
Labels: debt, dependencies

#52 Replace jar for JFontChooser with `com.rover12421.opensource:JFontChoose:1.0.5-3`
  build.gradle
  src/lib/net.mariottini.swing.jar
  src/main/java/listfix/view/dialogs/AppOptionsDialog.java
Labels: debt, dependencies

#60 Keep track of active tab/playlist in `GUIScreen`
  src/main/java/listfix/swing/IDocumentChangeListener.java
  src/main/java/listfix/swing/JDocumentComponent.java
  src/main/java/listfix/swing/JDocumentTabbedPane.java
  src/main/java/listfix/view/GUIScreen.java
Labels: internal

#57 Generate junit Test Report
  .github/workflows/ci.yml
Labels: DevOps

#71 Upgrade to JavaPackager 1.7.0-SNAPSHOT
  build.gradle
Labels: dependencies

#32 Update dependencies: javafx-gradle-plugin 0.0.13 & io.github.fvarrui:javapackager 1.7.0
  build.gradle
Labels: dependencies

#61 Add "Open in Explorer" for playlists
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/controls/PlaylistEditCtrl.java
Labels: enhancement

#72 Fix NullPointer exception when running Deep-fix button.
  src/main/java/listfix/model/BatchRepair.java
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/controls/PlaylistsList.java
  src/main/java/listfix/view/dialogs/AppOptionsDialog.java
  src/main/java/listfix/view/dialogs/BatchClosestMatchResultsDialog.java
  src/main/java/listfix/view/dialogs/DualProgressDialog.java
  src/main/java/listfix/view/dialogs/EditFilenameDialog.java
  src/main/java/listfix/view/dialogs/MultiListBatchClosestMatchResultsDialog.java
  src/main/java/listfix/view/dialogs/PlaylistsTableModel.java
  src/main/java/listfix/view/dialogs/ReorderPlaylistDialog.java
  src/main/java/listfix/view/support/DualProgressAdapter.java
  src/main/java/listfix/view/support/DualProgressWorker.java
  src/main/java/listfix/view/support/FontExtensions.java
  src/main/java/listfix/view/support/ICloseableTabManager.java
  src/main/java/listfix/view/support/IDualProgressObserver.java
  src/main/java/listfix/view/support/IPlaylistModifiedListener.java
  src/main/java/listfix/view/support/IProgressObserver.java
  src/main/java/listfix/view/support/ImageIcons.java
  src/main/java/listfix/view/support/PlaylistTreeNode.java
  src/main/java/listfix/view/support/ProgressAdapter.java
  src/main/java/listfix/view/support/ProgressWorker.java
  src/main/java/listfix/view/support/SplashScreen.java
  src/main/java/listfix/view/support/WindowSaver.java
  src/main/java/listfix/view/support/ZebraJTable.java
Labels: bug

#73 Fix exception when closing tabs.
  src/main/java/listfix/controller/GUIDriver.java
  src/main/java/listfix/controller/MediaLibraryOperator.java
  src/main/java/listfix/controller/Task.java
  src/main/java/listfix/exceptions/MediaDirNotFoundException.java
  src/main/java/listfix/exceptions/UnsupportedPlaylistFormat.java
  src/main/java/listfix/io/playlists/IPlaylistReader.java
  src/main/java/listfix/io/playlists/PlaylistReader.java
  src/main/java/listfix/io/playlists/PlaylistReaderFactory.java
  src/main/java/listfix/io/playlists/PlaylistWriterFactory.java
  src/main/java/listfix/io/playlists/itunes/ITunesXMLReader.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
  src/main/java/listfix/io/playlists/m3u/M3UWriter.java
  src/main/java/listfix/io/playlists/pls/PLSReader.java
  src/main/java/listfix/io/playlists/wpl/WPLReader.java
  src/main/java/listfix/io/playlists/xspf/XSPFReader.java
  src/main/java/listfix/json/JsonAppOptions.java
  src/main/java/listfix/json/JsonMediaLibrary.java
  src/main/java/listfix/model/enums/PlaylistType.java
  src/main/java/listfix/model/playlists/Playlist.java
  src/main/java/listfix/swing/JDocumentTabbedPane.java
  src/main/java/listfix/util/UnicodeUtils.java
  src/main/java/listfix/view/dialogs/BatchExactMatchesResultsDialog.java
  src/test/java/listfix/model/playlists/PlaylistFactoryTest.java
  src/test/java/listfix/util/TestUtil.java
  src/test/resources/playlists/m3u/aight.m3u8
Labels: internal

#77 Fix reading M3U8 with BOM
  src/main/java/listfix/io/UnicodeInputStream.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
Labels: bug, internal

#78 Remove code duplication between M3UReader & WPLReader
  src/main/java/listfix/io/playlists/PlaylistReader.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
  src/main/java/listfix/io/playlists/wpl/WPLReader.java
Labels: debt

#85 Fix progress bar
  src/main/java/listfix/io/BufferedProgressReader.java
  src/main/java/listfix/io/playlists/PlaylistReader.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
  src/main/java/listfix/view/support/ProgressAdapter.java
Labels: bug

#90 Fix `isModified` flag in playlist
  src/main/java/listfix/model/playlists/Playlist.java
Labels: bug

#86 Fix reading WPL playlists
  src/test/java/listfix/io/playlists/wpl/WPLReaderTests.java
  src/test/resources/playlists/wpl/2seq.wpl
  src/test/resources/playlists/wpl/playlist.wpl
Labels: debt

#89 Fix `NullPointerException` in `PlaylistEditCtrl`
  build.gradle
  src/main/java/listfix/config/IAppOptions.java
  src/main/java/listfix/config/IApplicationConfiguration.java
  src/main/java/listfix/controller/ListFixController.java
  src/main/java/listfix/controller/MediaLibraryOperator.java
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/IListFixGui.java
  src/main/java/listfix/view/controls/PlaylistEditCtrl.java
  src/main/java/listfix/view/dialogs/BatchExactMatchesResultsDialog.java
Labels: bug

#92 Closes playlist editor upon deletion from playlist directory component.
  src/main/java/listfix/swing/JDocumentTabbedPane.java
  src/main/java/listfix/view/FileEditor.java
  src/main/java/listfix/view/GUIScreen.java
Labels: bug

#87 Improve rename file in playlist directory
  src/main/java/listfix/view/GUIScreen.java
Labels: improvement

#93 Support for multiple playlist folders
  src/main/java/listfix/comparators/DirectoryThenFileThenAlphabeticalPathComparator.java
  src/main/java/listfix/config/IAppOptions.java
  src/main/java/listfix/config/IMediaLibrary.java
  src/main/java/listfix/config/JsonConfigFile.java
  src/main/java/listfix/config/MediaLibraryConfiguration.java
  src/main/java/listfix/controller/ListFixController.java
  src/main/java/listfix/controller/MediaLibraryOperator.java
  src/main/java/listfix/io/Constants.java
  src/main/java/listfix/io/FileTreeNodeGenerator.java
  src/main/java/listfix/io/FileUtils.java
  src/main/java/listfix/io/IPlaylistOptions.java
  src/main/java/listfix/io/PlaylistScanner.java
  src/main/java/listfix/io/TreeNodeFile.java
  src/main/java/listfix/io/filters/AudioFileFilter.java
  src/main/java/listfix/io/filters/FileExtensionFilterBase.java
  src/main/java/listfix/io/filters/PlaylistFileFilter.java
  src/main/java/listfix/io/playlists/PlaylistReaderFactory.java
  src/main/java/listfix/io/playlists/PlaylistWriterFactory.java
  src/main/java/listfix/json/JsonAppOptions.java
  src/main/java/listfix/json/JsonMediaLibrary.java
  src/main/java/listfix/model/BatchRepairItem.java
  src/main/java/listfix/model/playlists/FilePlaylistEntry.java
  src/main/java/listfix/model/playlists/Playlist.java
  src/main/java/listfix/swing/IDocumentChangeListener.java
  src/main/java/listfix/swing/JClosableTabComponent.java
  src/main/java/listfix/swing/JDocumentComponent.java
  src/main/java/listfix/swing/JDocumentTabbedPane.java
  src/main/java/listfix/util/FileNameTokenizer.java
  src/main/java/listfix/util/FileTypeSearch.java
  src/main/java/listfix/view/FileEditor.java
  src/main/java/listfix/view/GUIScreen.form
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/IListFixGui.java
  src/main/java/listfix/view/controls/JTransparentTextArea.java
  src/main/java/listfix/view/controls/PlaylistEditCtrl.java
  src/main/java/listfix/view/dialogs/AppOptionsDialog.form
  src/main/java/listfix/view/dialogs/AppOptionsDialog.java
  src/main/java/listfix/view/support/ITooltipable.java
  src/main/java/listfix/view/support/PlaylistTreeNode.java
  src/main/java/listfix/view/support/TreeTooltipRenderer.java
  src/main/resources/log4j2.yaml
  src/test/java/listfix/playlists/itunes/ITunesPlaylistTests.java
Labels: enhancement

#101 Update to Junit 5
  build.gradle
  src/test/java/listfix/config/MediaLibraryConfigurationTests.java
  src/test/java/listfix/io/FileUtilsTests.java
  src/test/java/listfix/io/playlists/m3u/M3UReaderTests.java
  src/test/java/listfix/io/playlists/wpl/WPLReaderTests.java
  src/test/java/listfix/model/playlists/PlaylistEntryTests.java
  src/test/java/listfix/model/playlists/PlaylistFactoryTests.java
  src/test/java/listfix/playlists/itunes/ITunesPlaylistTests.java
Labels: DevOps

#110 Deduplicate repair exact & closest match loop
  src/main/java/listfix/model/BatchRepair.java
  src/main/java/listfix/model/IRepairItem.java
Labels: debt

#114 Fix being able to delete folder from Playlists-Directories panel
  src/main/java/listfix/io/FileTreeNodeGenerator.java
  src/main/java/listfix/io/FileUtils.java
  src/main/java/listfix/view/GUIScreen.java
Labels: bug

#115 Use `io.github.borewit:lizzy` from Maven Central
  build.gradle
  src/lib/lizzy.jar
Labels: dependencies

#113 Be able to drag playlist folders into Playlists-Directories panel
  src/main/java/listfix/view/GUIScreen.java
Labels: enhancement

#111 Adjust total progress based on partial task progress
  src/main/java/listfix/comparators/MatchedPlaylistEntryComparator.java
  src/main/java/listfix/controller/Task.java
  src/main/java/listfix/controller/tasks/WriteMediaLibraryIniTask.java
  src/main/java/listfix/io/FileTreeNodeGenerator.java
  src/main/java/listfix/io/WinampHelper.java
  src/main/java/listfix/io/playlists/PlaylistWriter.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
  src/main/java/listfix/io/playlists/pls/PLSProperties.java
  src/main/java/listfix/io/playlists/pls/PLSReader.java
  src/main/java/listfix/io/playlists/wpl/WPLReader.java
  src/main/java/listfix/io/playlists/xspf/XSPFReader.java
  src/main/java/listfix/model/BatchRepair.java
  src/main/java/listfix/model/IRepairItem.java
  src/main/java/listfix/model/playlists/Playlist.java
  src/main/java/listfix/model/playlists/PlaylistEntry.java
  src/main/java/listfix/view/dialogs/BatchClosestMatchResultsDialog.form
  src/main/java/listfix/view/dialogs/BatchExactMatchesResultsDialog.form
  src/main/java/listfix/view/dialogs/BatchExactMatchesResultsDialog.java
  src/main/java/listfix/view/dialogs/DualProgressDialog.form
  src/main/java/listfix/view/dialogs/DualProgressDialog.java
  src/main/java/listfix/view/dialogs/MultiListBatchClosestMatchResultsDialog.java
  src/main/java/listfix/view/support/DualProgressAdapter.java
  src/main/java/listfix/view/support/DualProgressWorker.java
  src/main/java/listfix/view/support/ProgressAdapter.java
Labels: improvement

#112 Save windows locations in JSON application configuration
  src/main/java/listfix/config/IAppOptions.java
  src/main/java/listfix/config/IApplicationConfiguration.java
  src/main/java/listfix/config/IApplicationState.java
  src/main/java/listfix/controller/ListFixController.java
  src/main/java/listfix/json/JsonAppOptions.java
  src/main/java/listfix/json/JsonApplicationState.java
  src/main/java/listfix/json/JsonFrameSettings.java
  src/main/java/listfix/view/GUIScreen.java
  src/main/java/listfix/view/support/WindowSaver.java
Labels: debt

#123 Prevent exception being thrown when comparing different `Path` types
  src/main/java/listfix/model/playlists/FilePlaylistEntry.java
Labels: bug

#124 Fix a number of JavaDoc errors
  src/main/java/listfix/io/playlists/IPlaylistReader.java
  src/main/java/listfix/io/playlists/m3u/M3UReader.java
  src/main/java/listfix/io/playlists/pls/PLSProperties.java
  src/main/java/listfix/io/playlists/pls/PLSReader.java
  src/main/java/listfix/io/playlists/wpl/WPLReader.java
  src/main/java/listfix/io/playlists/wpl/WPLWriter.java
  src/main/java/listfix/io/playlists/xspf/XSPFReader.java
  src/main/java/listfix/model/playlists/FilePlaylistEntry.java
Labels: internal
